# This is a basic workflow to help you get started with Actions

name: style

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  black:
    name: Style Reformatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python_version: "3.8"
      - run: "make reformat"
        continue-on-error: true
        name: Style reformatting
      - name: Commit changes
        continue-on-error: true
        run: |
          git config --local committer.email "noreply@github.com"
          git config --local committer.name "GitHub"
          git config --local author.email "${{ github.actor }}@users.noreply.github.com"
          git config --local author.name "{{ github.actor }}"
          git add -A
          git commit -m "Style Reformatting"
          git push "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:${GITHUB_REF#refs/heads/}
